using Discord;
using Discord.Commands;
using Discord.WebSocket;
using Rosettes.core;
using Rosettes.modules.commands;

namespace Rosettes.modules.engine
{
    public static class CommandEngine
    {
        private static readonly CommandService _commands = ServiceManager.GetService<CommandService>();

        public static async Task LoadCommands()
        {
            // Load all the commands from their modules
            // The order in which commands are listed is the ordewr
            // in which they are listed.
            await _commands.AddModuleAsync<UtilityCommands>(null);
            await _commands.AddModuleAsync<RandomCommands>(null);
            await _commands.AddModuleAsync<MusicCommands>(null);
            await _commands.AddModuleAsync<GameCommands>(null);
            await _commands.AddModuleAsync<DumbCommands>(null);
            
            // always load UnlistedCommands last.
            await _commands.AddModuleAsync<UnlistedCommands>(null);
        }

        public static async Task HandleCommand(SocketCommandContext context, int argPos)
        {
            var user = await UserEngine.GetDBUser(context.User);
            if (user.CanUseCommand(context.Guild))
            {
                await _commands.ExecuteAsync(context: context, argPos: argPos, services: ServiceManager.Provider);
            }
            else
            {
                await context.Message.AddReactionAsync(new Emoji("⌚"));
            }
        }

        public static void CreateCommandPage()
        {
            if (!Directory.Exists("/var/www/html/rosettes/"))
            {
                Directory.CreateDirectory("/var/www/html/rosettes/");
            }

            string webContents = $"<p><small>This page is autogenerated by Rosettes every time it restarts. Last update: {DateTime.UtcNow:ddd, dd MMM yyy; HH:mm:ss GMT}</small></p>\n";

            ModuleInfo? currModule = null;
            var comms = ServiceManager.GetService<CommandService>();
            foreach (CommandInfo singleCommand in comms.Commands)
            {
                // Every module has it's own list message to avoid surpasing the 2000char limit.
                if (singleCommand.Module.Name == "UnlistedCommands") break;
                if (currModule == null || currModule.Name != singleCommand.Module.Name)
                {
                    currModule = singleCommand.Module;
                    webContents += $"<hr>\n<p><b>{currModule.Summary}</b></p>\n";
                }
                webContents += $"<p><b>{Settings.Prefix}{singleCommand.Name}</b><br>\n";
                if (singleCommand.Summary != null)
                {
                    webContents += $"{singleCommand.Summary}</p>\n";
                }
                else
                {
                    webContents += $"&nbsp;</p>\n";
                }
            }
            using var writer = File.CreateText("/var/www/html/rosettes/commands.html");

            writer.Write(webContents);

            writer.Close();
        }
    }
}
